# Site settings
title: My journey as a Software Development Student
header-img: img/home-bg.png
email: asabogal.git@gmail.com
copyright_name: asabogal
description: > # this means to ignore newlines until "baseurl:"
  With advice for new students
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  asabogal
learn_profile: asabogal
email_username: asabogal.git@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
